### PR TITLE
Migrate from class to hooks

### PR DESCRIPTION
**Pull request by CharlyJazz**
- Update react to 16.8.0

- Prevent warnings about the deprecation of react class removing it and write the component hcaptcha with hooks

- Expose to parent component resetCaptcha and execute functions

Closes https://github.com/hCaptcha/react-hcaptcha/issues/41

### CODE REVIEW

**Comment by gaieges** [comment]
Have a chance to take a look at this @mtratsiuk @brdlyptrs @jjanii

**Comment by brdlyptrs** [comment]
Hi @CharlyJazz, thanks for the PR. May I ask why you feel this is needed, and what does it attempt to solve? From my perspective this is a large rewrite with no tests, currently. It can aslo be more prone to unwanted re-renders or unnecessary handler calls with any future updates. Last comment, the code seems less legible here, do you find this easier to understand if you were to quickly glance over this?

**Comment by CharlyJazz** [comment]
1. Class component are deprecated
2. Hooks have better perfomance
3. Hooks have less file size

This is the way React works now, readability is a relative issue. React programmers have to get used to a functional style and this is how it looks. OOP with React is already deprecated. There is a lot of information about this on the internet.

But I agree this project should have unit tests and integration with cypress and some pipeline like travis ci

**Comment by mtratsiuk** [comment]
> 1. Class component are deprecated
> 2. Hooks have better perfomance
> 3. Hooks have less file size
> 
> This is the way React works now, readability is a relative issue. React programmers have to get used to a functional style and this is how it looks. OOP with React is already deprecated. There is a lot of information about this on the internet.
> 
> But I agree this project should have unit tests and integration with cypress and some pipeline like travis ci

Adding some thoughts as well, if I may. Its obvious that react community is moving towards using hooks, however I don't think we should just do it without other considerations. The main problem here is of course absence of test coverage while this PR is a big change, however:

> 1. Class component are deprecated

Could you please link the source of that info? This is what I see in the react docs: https://reactjs.org/docs/hooks-faq.html#do-i-need-to-rewrite-all-my-class-components

> 2. Hooks have better perfomance

I'm not sure its that simple. Could you provide any benchmark / link to react docs proving that?
This is what I managed to find - https://reactjs.org/docs/hooks-faq.html#are-hooks-slow-because-of-creating-functions-in-render. It doesn't say hooks have better performance, its trying to convince the reader that hooks aren't significantly worse and, if used correctly, could be better.

> 3. Hooks have less file size

This is doubtful as well, I believe it depends on different factors. Don't forget that you might need to add some `React.useCallback` etc in code with hooks.

>React programmers have to get used to a functional style and this is how it looks. OOP with React is already deprecated. 

Thats an interesting topic. I personally don't think changing class component to function with hooks makes it more "functional" or less "OOP" :slightly_smiling_face: If by "functional style" you mean "code with functions instead of classes", then I think you are right. However if you meant functional programming paradigm (as opposed to OOP), then I don't believe functional react component with hooks has anything to do with it (e.g. `useEffect` hook even has it in it's name - "side effects" :slightly_smiling_face: )

**Comment by CharlyJazz** [comment]
So sorry, i going to close PR, You right guys, this PR is a lose of time!

**Pull request closed without merging**
